/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VMFStaking__factory } from "./VMFStaking__factory";
export { VMFToken__factory } from "./VMFToken__factory";
