/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VMFStaking {
  export type StakingInfoStruct = {
    id: BigNumberish;
    startTime: BigNumberish;
    stakingPeriod: BigNumberish;
    stakedAmount: BigNumberish;
    lastYieldClaimAt: BigNumberish;
  };

  export type StakingInfoStructOutput = [
    id: bigint,
    startTime: bigint,
    stakingPeriod: bigint,
    stakedAmount: bigint,
    lastYieldClaimAt: bigint
  ] & {
    id: bigint;
    startTime: bigint;
    stakingPeriod: bigint;
    stakedAmount: bigint;
    lastYieldClaimAt: bigint;
  };
}

export interface VMFStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_minimumAPRRate"
      | "_userStakingInfo"
      | "calculateCompound"
      | "calculateStakeYield"
      | "extendStakingPeriod"
      | "getUserStakingInfo"
      | "getWithdrawableAmount"
      | "idCounter"
      | "maximumStakeCap"
      | "minimumRate"
      | "minimumStakeCap"
      | "owner"
      | "renounceOwnership"
      | "setMaximumStakeCap"
      | "setMinimumStakeCap"
      | "stake"
      | "stakeBatch"
      | "token"
      | "transferOwnership"
      | "withdraw"
      | "withdrawAll"
      | "withdrawBatch"
      | "withdrawYield"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Stake"
      | "StakeYieldWithdraw"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_minimumAPRRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_userStakingInfo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCompound",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateStakeYield",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "extendStakingPeriod",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakingInfo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawableAmount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "idCounter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maximumStakeCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumStakeCap",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaximumStakeCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumStakeCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeBatch",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAll",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBatch",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawYield",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "_minimumAPRRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_userStakingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCompound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateStakeYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendStakingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idCounter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maximumStakeCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumStakeCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaximumStakeCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumStakeCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawYield",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    stakedAmount: BigNumberish,
    stakingPeriod: BigNumberish,
    startTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    stakedAmount: bigint,
    stakingPeriod: bigint,
    startTime: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    stakedAmount: bigint;
    stakingPeriod: bigint;
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeYieldWithdrawEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    stakedAmount: BigNumberish,
    yieldWithdrawalAmount: BigNumberish,
    stakingPeriod: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    stakedAmount: bigint,
    yieldWithdrawalAmount: bigint,
    stakingPeriod: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    stakedAmount: bigint;
    yieldWithdrawalAmount: bigint;
    stakingPeriod: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    stakedAmount: BigNumberish,
    withdrawAmount: BigNumberish,
    stakingPeriod: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    stakedAmount: bigint,
    withdrawAmount: bigint,
    stakingPeriod: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    stakedAmount: bigint;
    withdrawAmount: bigint;
    stakingPeriod: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VMFStaking extends BaseContract {
  connect(runner?: ContractRunner | null): VMFStaking;
  waitForDeployment(): Promise<this>;

  interface: VMFStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _minimumAPRRate: TypedContractMethod<[], [bigint], "view">;

  _userStakingInfo: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        startTime: bigint;
        stakingPeriod: bigint;
        stakedAmount: bigint;
        lastYieldClaimAt: bigint;
      }
    ],
    "view"
  >;

  calculateCompound: TypedContractMethod<
    [_ratio: BigNumberish, _principal: BigNumberish, _n: BigNumberish],
    [bigint],
    "view"
  >;

  calculateStakeYield: TypedContractMethod<
    [_ratio: BigNumberish, _principal: BigNumberish, _n: BigNumberish],
    [bigint],
    "view"
  >;

  extendStakingPeriod: TypedContractMethod<
    [id: BigNumberish, stakingPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  getUserStakingInfo: TypedContractMethod<
    [_user: AddressLike, _stakingId: BigNumberish],
    [VMFStaking.StakingInfoStructOutput],
    "view"
  >;

  getWithdrawableAmount: TypedContractMethod<
    [_id: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;

  idCounter: TypedContractMethod<[], [bigint], "view">;

  maximumStakeCap: TypedContractMethod<[], [bigint], "view">;

  minimumRate: TypedContractMethod<[], [bigint], "view">;

  minimumStakeCap: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMaximumStakeCap: TypedContractMethod<
    [_newCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinimumStakeCap: TypedContractMethod<
    [_newCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [amount: BigNumberish, stakingPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeBatch: TypedContractMethod<
    [amounts: BigNumberish[], stakingPeriods: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [_id: BigNumberish, _withdrawAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawAll: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  withdrawBatch: TypedContractMethod<
    [ids: BigNumberish[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  withdrawYield: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_minimumAPRRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "_userStakingInfo"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        startTime: bigint;
        stakingPeriod: bigint;
        stakedAmount: bigint;
        lastYieldClaimAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateCompound"
  ): TypedContractMethod<
    [_ratio: BigNumberish, _principal: BigNumberish, _n: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateStakeYield"
  ): TypedContractMethod<
    [_ratio: BigNumberish, _principal: BigNumberish, _n: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "extendStakingPeriod"
  ): TypedContractMethod<
    [id: BigNumberish, stakingPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getUserStakingInfo"
  ): TypedContractMethod<
    [_user: AddressLike, _stakingId: BigNumberish],
    [VMFStaking.StakingInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawableAmount"
  ): TypedContractMethod<
    [_id: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "idCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maximumStakeCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minimumRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minimumStakeCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaximumStakeCap"
  ): TypedContractMethod<[_newCap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinimumStakeCap"
  ): TypedContractMethod<[_newCap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [amount: BigNumberish, stakingPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeBatch"
  ): TypedContractMethod<
    [amounts: BigNumberish[], stakingPeriods: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [_id: BigNumberish, _withdrawAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawAll"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawBatch"
  ): TypedContractMethod<
    [ids: BigNumberish[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawYield"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Stake"
  ): TypedContractEvent<
    StakeEvent.InputTuple,
    StakeEvent.OutputTuple,
    StakeEvent.OutputObject
  >;
  getEvent(
    key: "StakeYieldWithdraw"
  ): TypedContractEvent<
    StakeYieldWithdrawEvent.InputTuple,
    StakeYieldWithdrawEvent.OutputTuple,
    StakeYieldWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Stake(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      StakeEvent.InputTuple,
      StakeEvent.OutputTuple,
      StakeEvent.OutputObject
    >;
    Stake: TypedContractEvent<
      StakeEvent.InputTuple,
      StakeEvent.OutputTuple,
      StakeEvent.OutputObject
    >;

    "StakeYieldWithdraw(address,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      StakeYieldWithdrawEvent.InputTuple,
      StakeYieldWithdrawEvent.OutputTuple,
      StakeYieldWithdrawEvent.OutputObject
    >;
    StakeYieldWithdraw: TypedContractEvent<
      StakeYieldWithdrawEvent.InputTuple,
      StakeYieldWithdrawEvent.OutputTuple,
      StakeYieldWithdrawEvent.OutputObject
    >;

    "Withdraw(address,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
